version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0-browsers-legacy
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.1-always-
            - npm-v2.1-{{ checksum "gatsby/package-lock.json" }}
            - composer-v2.1-{{ checksum "~/.composer/composer.lock" }}
      - run:
          name: Prep Environment
          command: |
            sudo apt install -y rsync composer php-xml
            composer global require pantheon-systems/terminus
            cd ~/build/gatsby
            sudo npm install -g gatsby
            npm install
      - run:
          name: Import GitHub Token
          command: |
            cd ~/build/gatsby
            touch .env.production
            echo "GITHUB_API=$GITHUB_TOKEN" > .env.production
      - run:
          name: Gatsby Build
          command: |
            cd ~/build/gatsby
            gatsby build --prefix-paths
      - run:
          name: Remove empty directories
          command: |
            find ~/build/gatsby/public -type d -empty -delete
      - run:
          name: Deploy Multidev environment
          command: |
            bash ./scripts/deploy-multidev.sh
#      - run:
#          name: Start Ghost Driver
#          command: phantomjs --webdriver=8643
#          background: true
#      - run:
#          name: Start Gatsby
#          command: |
#            cd ~/build/gatsby
#            gatsby serve --prefix-paths
#          background: true
#      - run:
#          name: Wait for Gatsby
#          command: dockerize -wait tcp://localhost:9000 -timeout 1m
#      - run:
#          name: Behat
#          command: |
#            cd ~/build
#            npm install
#            ~/build/bin/behat
#      - run:
#          name: a11y
#          command: |
#            /documentation/node_modules/.bin/grunt test
#      - run:
#          name: Merge Conflicts
#          command: |
#            scripts/merge_conflicts.sh
#      - run:
#          name: htmlProofer
#          command: |
#            htmlproofer --assume-extension  ./output_prod/ --disable-external true
#      - run:
#          name: Speedtest
#          command: |
#            echo
#            # Run sitespeed.io performance testing.
#            mkdir ~/build/artifacts
#            bash scripts/run-sitespeed-test.sh
      - save_cache:
          key: npm-v2.1-{{ checksum "gatsby/package-lock.json" }}
          paths:
            - ~/build/gatsby/node_modules
      - save_cache:
          key: composer-v2.1-{{ checksum "~/.composer/composer.lock" }}
          paths:
            - ~/.composer/cache
      - save_cache:
          key: v2.1-always-{{ epoch }}
          paths:
            - ~/build/gatsby/public
            - ~/build/gatsby/.cache
#      - store_artifacts:
#          path: ~/build/sitespeed-result

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy-live.sh
            fi


# Below is CircleCI 1.0 Config Syntax that is still supported on CircleCI 2.0
experimental:
  notify:
    branches:
      only:
        - master
